### ISSUE TITLE
Missing validations and database constrains

### ISSUE THREAD

**Issue by ghost** [TAMULib/EIDER#25]
Missing validations

Entity
- url => NotNull

Identifier
- identifier => NotNull

IdentifierType
- namespace => NotNull
- name => NotNull

Name
- name => NotNull

Missing database constraints

Entity
- url => nullable = false

Identifier
- identifier => nullable = false

IdentifierType
- namespace => nullable = false
- name => nullable = false

Name
- name => nullable = false

**Comment by wwelling** [comment]
Should identifier type be optional on identifier?

Should
