### ISSUE TITLE
Upgrade EIDER Spring dependencies (Spring Boot 2.6.7)

### ISSUE THREAD

**Issue by ghost** [TAMULib/EIDER#40]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide

- [x] Upgrade Spring-Boot parent and dependencies
- [x] Upgrade all dependencies with vulnerabilities
- [x] Upgrade tests to use exclusively JUnit5
- [x] Passes CI (all tests if no CI configured)
- [x] Replace deprecated code
- [x] Provides a Dockerfile

> If a certain dependency upgrade or deprecated code replacement ends up being large in size, create an issue.

> Document procedure followed to do the upgrades on the app - insofar as it varies from the previously documented apps.

**Comment by kaladay** [comment]
I retroactively updated this from needing 2.6.6 to instead be needing 2.6.7.
