### ISSUE TITLE
Models should have limits on name property length

### ISSUE THREAD

**Issue by rladdusaw** [TAMULib/EIDER#7]
Entity canonicalName
IdentifierType name
Name name

Currently using a placeholder of 250 max and no minimum.

**Comment by ghost** [comment]
- Entity canonicalName 2 255
- Entity notes 0 1024
- Identifier identifier 4 64
- Identifier notes 0 1024
- Identifier Type name 4 128
- Name name 2 255
- Name notes 0 1024
